using Documenter, Literate
import SquareIsingModel as Ising

#=
We place Literate.jl source .jl files and the generated .md files inside docs/src/literate.
=#
const literate_dir = joinpath(@__DIR__, "src/literate")

#=
Helper function to remove all "*.md" files from a directory.
=#
function clear_md_files(dir::String)
    for file in readdir(dir; join=true)
        if endswith(file, ".md")
            rm(file)
        end
    end
end

#=
Remove previously Literate.jl generated files. This removes all "*.md" files inside
`literate_dir`. This is a precaution: if we build docs locally and something fails,
and then change the name of a source file (".jl"), we will be left with a lingering
".md" file which will be included in the docs build. The following line makes sure
that doesn't happen.
=#
clear_md_files(literate_dir)

#=
Run Literate.jl on the .jl source files within docs/literate.
This creates the markdown .md files inside docs/src/literate,
with the same name but with the extension changes (.jl -> .md).
=#
for file in readdir(literate_dir; join=true)
    if endswith(file, ".jl")
        Literate.markdown(file, literate_dir)
    end
end

#=
Build docs.
=#
makedocs(
    modules = [Ising],
    sitename = "SquareIsingModel.jl",
    pages = [
        "Home" => "index.md",
        "The Ising Model" => "ising.md",
        "Examples (MD)" => [
            "Metropolis sampler" => "examples/metropolis.md",
            "Wolff sampler" => "examples/wolff.md",
            "Hybrid sampler" => "examples/hybrid.md",
        ],
        "Examples (Literate)" => [
            "Metropolis" => "literate/metropolis.md",
            "Metropolis+f(M)" => "literate/metropolis_f.md",
        ],
        "Reference" => "reference.md"
    ],
    strict = true
)

#=
After the docs have been compiled, we can remove the *.md files generated by Literate.
=#
clear_md_files(literate_dir)

#=
Deploy docs to Github pages.
=#
deploydocs(
    repo = "github.com/cossio/SquareIsingModel.jl.git",
    devbranch = "main"
)
